### ISSUE TITLE
Update sonarqube-scan-action from v4.1.0 to v5.0.0

### ISSUE THREAD

**Issue by yuramax** [boarlabsxyz/Kavoon#219]
We have issue with deploy to production and want to update version for SonarQube Scan

```
- name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v4.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
```

Changes should be implemented in `production.yaml`.
